// Library crate — all modules are public so integration tests can import them.
pub mod batch;
#[cfg(feature = "c2pa")]
pub mod c2pa;
pub mod cli;
pub mod dct;
pub mod dwt;
pub mod dwt_embed;
pub mod embed;
pub mod extract;
pub mod geometry;
pub mod info;
pub mod keying;
#[cfg(feature = "learned")]
pub mod learned;
pub mod signal;
pub mod spread_spectrum;
pub mod strip;
pub mod verify;
